---
- name: reload systemd
  systemd:
    daemon_reload: true

- name: restart kube-proxy
  service:
    name: kube-proxy
    state: restarted

- name: restart kubelet
  service:
    name: kubelet
    state: restarted
