---
# Copyright (C) 2023 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Setup K8s worker
  hosts: k8s_worker
  become: true
  gather_facts: true
  tasks:
    - name: Setup Kubernetes worker
      when:
        - k8s_worker_setup_networking is not defined
      ansible.builtin.include_role:
        name: githubixx.kubernetes-worker

- name: Setup Cilium
  hosts: k8s_worker
  become: true
  gather_facts: true
  tasks:
    - name: Include Cilium role
      when:
        - k8s_worker_setup_networking is defined
        - k8s_worker_setup_networking == "install"
      ansible.builtin.include_role:
        name: githubixx.cilium_kubernetes
      vars:
        cilium_action: "install"

- name: Setup tooling to make worker nodes usable
  hosts: test-assets
  become: true
  gather_facts: true
  tasks:
    - name: Setup tooling
      when:
        - k8s_worker_setup_networking is defined
        - k8s_worker_setup_networking == "install"
      block:
        - name: Waiting for Cilium to become ready
          ansible.builtin.include_tasks:
            file: tasks/cilium_status.yml
      
        - name: Control plane nodes should only run Cilium pods
          ansible.builtin.include_tasks:
            file: tasks/taint_controller_nodes.yml
      
        - name: Install CoreDNS
          ansible.builtin.include_tasks:
            file: tasks/coredns.yml
      
        - name: Waiting for CoreDNS to become ready
          ansible.builtin.include_tasks:
            file: tasks/coredns_status.yml
